// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/account" | "/account/calendar" | "/account/history" | "/account/pay" | "/account/pay/done" | "/account/pay/go/[id]" | "/account/profile" | "/admin/studio" | "/admin/studio/calendar" | "/admin/studio/debts" | "/admin/studio/groups" | "/admin/studio/ledger" | "/admin/studio/people" | "/admin/studio/session/[id]" | "/login"
type AppRouteHandlerRoutes = "/api/bunny-token" | "/api/check-payment-ru" | "/api/create-checkout-polar" | "/api/create-payment-ru" | "/api/health" | "/api/submit" | "/api/webhook-paddle" | "/api/webhook-payplus" | "/api/webhook-polar" | "/api/webhook-yookassa"
type PageRoutes = never
type LayoutRoutes = "/" | "/account" | "/admin"
type RedirectRoutes = "/"
type RewriteRoutes = "/" | "/agreement" | "/camp" | "/consent-data" | "/consent-marketing" | "/embroidery" | "/israeli-hints" | "/materials" | "/materials2" | "/portfolio" | "/privacy" | "/privacy-ru" | "/refunds" | "/register" | "/studio" | "/terms" | "/video"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/account": {}
  "/account/calendar": {}
  "/account/history": {}
  "/account/pay": {}
  "/account/pay/done": {}
  "/account/pay/go/[id]": { "id": string; }
  "/account/profile": {}
  "/admin": {}
  "/admin/studio": {}
  "/admin/studio/calendar": {}
  "/admin/studio/debts": {}
  "/admin/studio/groups": {}
  "/admin/studio/ledger": {}
  "/admin/studio/people": {}
  "/admin/studio/session/[id]": { "id": string; }
  "/agreement": {}
  "/api/bunny-token": {}
  "/api/check-payment-ru": {}
  "/api/create-checkout-polar": {}
  "/api/create-payment-ru": {}
  "/api/health": {}
  "/api/submit": {}
  "/api/webhook-paddle": {}
  "/api/webhook-payplus": {}
  "/api/webhook-polar": {}
  "/api/webhook-yookassa": {}
  "/camp": {}
  "/consent-data": {}
  "/consent-marketing": {}
  "/embroidery": {}
  "/israeli-hints": {}
  "/login": {}
  "/materials": {}
  "/materials2": {}
  "/portfolio": {}
  "/privacy": {}
  "/privacy-ru": {}
  "/refunds": {}
  "/register": {}
  "/studio": {}
  "/terms": {}
  "/video": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/account": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
