// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/account/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/account/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/history">> = Specific
  const handler = {} as typeof import("../../src/app/account/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../src/app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/pay/done/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/pay/done">> = Specific
  const handler = {} as typeof import("../../src/app/account/pay/done/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/pay/go/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/pay/go/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/account/pay/go/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/pay/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/pay">> = Specific
  const handler = {} as typeof import("../../src/app/account/pay/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/profile">> = Specific
  const handler = {} as typeof import("../../src/app/account/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/studio/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/studio/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/admin/studio/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/studio/debts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/studio/debts">> = Specific
  const handler = {} as typeof import("../../src/app/admin/studio/debts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/studio/groups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/studio/groups">> = Specific
  const handler = {} as typeof import("../../src/app/admin/studio/groups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/studio/ledger/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/studio/ledger">> = Specific
  const handler = {} as typeof import("../../src/app/admin/studio/ledger/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/studio">> = Specific
  const handler = {} as typeof import("../../src/app/admin/studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/studio/people/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/studio/people">> = Specific
  const handler = {} as typeof import("../../src/app/admin/studio/people/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/studio/session/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/studio/session/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/studio/session/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bunny-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bunny-token">> = Specific
  const handler = {} as typeof import("../../src/app/api/bunny-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/check-payment-ru/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/check-payment-ru">> = Specific
  const handler = {} as typeof import("../../src/app/api/check-payment-ru/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/create-checkout-polar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/create-checkout-polar">> = Specific
  const handler = {} as typeof import("../../src/app/api/create-checkout-polar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/create-payment-ru/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/create-payment-ru">> = Specific
  const handler = {} as typeof import("../../src/app/api/create-payment-ru/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhook-paddle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook-paddle">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhook-paddle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhook-payplus/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook-payplus">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhook-payplus/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhook-polar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook-polar">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhook-polar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhook-yookassa/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook-yookassa">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhook-yookassa/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/account/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/account">> = Specific
  const handler = {} as typeof import("../../src/app/account/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
